name: PR Validation

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Install Playwright Browsers
        run: pwsh tests/Kairos.PlaywrightTests/bin/Release/net10.0/playwright.ps1 install --with-deps

      - name: Test
        run: dotnet run --project src/Kairos.Web -c Release & sleep 10 && dotnet test --no-build --verbosity normal -c Release
        env:
          ASPNETCORE_URLS: http://localhost:5111
